### ISSUE TITLE
JSON-LD snippet creates soft 404

### ISSUE THREAD

**Issue by Oliviacrenza** [the-working-party/shopify-cookbook#23]
The following code on the website makes Google to track the url of https://www.xxxremoved-for-privacy.com/search?q={query}, which generates a 200 error code as the search for {query} returns no result.

Can we replace the url with https://www.xxxremoved-for-privacy.com/search ?

Thank you!

--
  | <script type="application/ld+json">
  | {
  | "@context": "https://schema.org",
  | "@type": "WebSite",
  | "name": "Movo Photo","url": "https://www.xxxremoved-for-privacy.com",
  | "potentialAction": {
  | "@type": "SearchAction",
  | "target": "https://www.xxxremoved-for-privacy.com/search?q={query}",
  | "query-input": "required name=query"
  | }
  | }
  | </script>

**Comment by lloydstubber** [comment]
Thanks for pointing this out @Oliviacrenza. This has now been updated.
